name: Doc Publish

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    name: Publish Doc Site to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull latest main
        run: git pull origin main
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: docs-deploy
          aws-region: us-east-1
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'
          enable-cache: true
      - name: Publish
        run: |
            cd docs/python
            uv run build.py
            sudo apt update
            sudo apt-get install -y ruby ruby-dev jq
            sudo gem install bundler
            cd ../build
            cp ../../README.md _includes/project_readme.md
            cp ../../CHANGELOG.md _includes/project_changelog.md
            sudo bundle install
            sudo bundle exec jekyll build
            cd _site
            aws s3 sync --delete . s3://clearskies.info/modules/clear-skies-aws/
            cd ../../python
            aws s3 cp s3://clearskies.info/modules/manifest.json . || touch manifest.json
            uv run update_manifest.py --pyproject_file=../../pyproject.toml --modules_location=modules
            aws s3 cp manifest.json s3://clearskies.info/modules/manifest.json
